name: Core
main: com.levelmc.core.Core
author: maru, PetteriM1
version: "${pom.version}"
api: ["1.0.9"]

commands:
  chair:
    usage: "/chair <on|off>"
    description: "Enable/disable chairs"
    permission: "chair.toggle"

permissions:
  chair.toggle:
    default: true
    description: "Enable/disable chairs"